# Generated by Django 5.2.3 on 2025-07-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=20, unique=True)),
                ('productCategory', models.CharField(max_length=50)),
                ('productName', models.CharField(max_length=100)),
                ('productColor', models.CharField(max_length=50)),
                ('productImage', models.URLField(max_length=500)),
                ('productSize', models.CharField(max_length=50)),
                ('productQuantity', models.IntegerField()),
                ('productDescription', models.TextField()),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
